function plot_line_plot_4dir(n_reps)
% Used for 2 pixel bar stimuli 
% Generated by Burnett - 05/06/2024

%% Generate polar plot
    res_files = dir('RES_all_reps*');
    load(res_files(1).name, 'data_all_reps')

    angls = 0:90:270;
    
    for plot_n = 1:4
        figure
        if plot_n == 1
            % % % OFF
            % 20 dps
            values = [9, 2, 10, 1];
        elseif plot_n == 2
            % 100 dps
            values = [11, 4, 12, 3];
        elseif plot_n == 3
            % % % ON
            % 20 dps
            values = [104, 97, 105, 96];
        elseif plot_n == 4
            % 100 dps
            values = [106, 99, 107, 98];
        end 
    
        % Find baseline voltage across all reps and all conditions of the bar
        % stimulus. 
        % all_voltage_data = squeeze(data_all_reps(values, 3, 1:n_reps));
        % all_voltage_data = horzcat(all_voltage_data{:}); % reshape and unpack values in cell arrays. 
        % exp_baseline = median(all_voltage_data);
        
        for j = 1:4
            subplot(2, 2, j)
    
            idx = values(j);
            voltage_data = squeeze(data_all_reps(idx, 3, 1:n_reps));
            % Find the shortest length of a rep. 
            min_len = 1000000; % use 1000000 as a baseline. 
            for k = 1:n_reps
                dd = voltage_data{k};
                len_dd = length(dd);
                if len_dd<min_len
                    min_len = len_dd;
                end 
            end 
    
            % Collect voltage data from across the repetitions. 
            data_comb = zeros(n_reps, min_len);
            % For each rep, extract the relevant voltage data.
            for k = 1:n_reps
                da = voltage_data{k};
                data_comb(k, :) = da(1:min_len);
            end 
            av_resp = mean(data_comb);
        
            % PLOT REPS
            for ii = 1:n_reps
                if ii == 1
                    col = 'r';
                elseif ii == 2
                    col = [1, 0.71, 0.76];
                elseif ii == 3
                    col = [0.68, 0.85, 0.9];
                elseif ii == 4
                    col = 'b';
                elseif ii == 5
                    col = [0.6 0.6 0.6];
                end 
                plot(data_comb(ii, :), 'Color', col, 'LineWidth', 0.6); hold on
                ylim([-65 -20])
                box off 
                ax = gca;
                ax.TickDir = 'out';                
            end 
    
            % PLOT AVERAGE 
            plot(av_resp, 'Color', 'k', 'LineWidth', 2.5)
    
            title(angls(j))
        end
    
        if plot_n == 1
            sgtitle('OFF - 20 dps') 
        elseif plot_n == 2
            sgtitle('OFF - 100 dps') 
        elseif plot_n == 3
            sgtitle('ON - 20 dps') 
        elseif plot_n == 4
            sgtitle('ON - 100 dps') 
        end 

        f = gcf;
        f.Position = [563   428   468   619];
    end 

end


% f = gcf;
% f.Position = [440   303   842   744];











