function process_ds_probe_protocol_data(project_folder, date_folder)
    % Process the data generated by running the 'DS_Probe_Protocol'. 
    % Runs through all experiment folders in the 'date_folder'.
    
    % Before running this script, make sure to have created the
    % 'processing_settings.mat' file using the script: '/Users/burnettl/G4_Display_Tools-master/G4_Data_Analysis/new_data_processing/create_processing_settings.m'
    
    %% Paths to data and processing settings. 

    % These paths are hard-coded in this instance. Assuming they will stay the same. 
    processing_folder = '/Users/burnettl/Documents/Janelia/G4/2405_Jinyong_Experiments/Data/DS_probe_protocol_1REP_RightHemi_20Hz_05-22-24_09-09-09';
    processing_path = fullfile(processing_folder, 'processing_settings.mat');

    date_folder_path = fullfile(project_folder, date_folder); 
    cd(date_folder_path)

    % List the experiment folders for that day
    exp_folders = dir('SS*');
    n_exps = height(exp_folders);

    for idx = 1:n_exps
        exp_name  = exp_folders(idx).name;
        fly_folder_path = fullfile(date_folder_path, exp_name);
        cd(fly_folder_path)
        % Process the data
        process_data(fly_folder_path, processing_path)
    end 

    process_1REP_DS_data(project_folder, date_folder);

end 














